### ISSUE TITLE
Appoint a CTF board

### ISSUE THREAD

**Issue by nithlack-zz** [honk-ci/honkcon#4]
- [ ] Appoint Board
- [ ] Set Goals for CTF

**Comment by nithlack-zz** [comment]
@jeefy update?

**Comment by jeefy** [comment]
@nithlack I don't think this is a HonkCon-specific task and should probably get moved to the `honkctl` repo. 

That being said, I could see creating a "challenge team". At this point it would really just be @mrbobbytables and I, possibly @IanColdwater

I'm going to close this here and re-open it in the appropriate repo.
